CREATE DATABASE IF NOT EXISTS toDoList_db;
CHARACTER SET utf8mb4
COLLATE utf8mb4_general_ci;

USE toDoList_db;

CREATE TABLE IF NOT EXISTS TODOTHINGS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    task VARCHAR(255) NOT NULL,
    due_to_date DATE NOT NULL
);
